### ISSUE TITLE
getUserInputByType 분석 및 개선방향 고찰.

### ISSUE THREAD

**Issue by WonSang98** [parkgeonhu/property-chat-bot#4]
# getUserInputByType 분석 및 개선방향 고찰.

### 코드 전문
``` javascript
const getUserInputByType = (paramKey, paramValue) => {
    try {
        const info = answerInfo[paramKey]
        const type = info['type']
    } catch (err) {
        return;
    }
    const info = answerInfo[paramKey]
    const type = info['type']
    let result = {};
    if (type == 'text') {
        let key = info['condition_name']
        result[key] = paramValue
    } else if (type == 'choose') {
        let list = info['list']
        for (let entry of list) {
            let key = entry['condition_name']
            let value = entry['condition_value']
            if (paramValue == entry['item_name']) {
                result[key] = value;
                break;
            }
        }
    } else if (type == 'currency') {
        const { amount } = JSON.parse(paramValue);
        let key = info['condition_name']
        result[key] = amount
    }
    return result;
}

const pushConditionToDict = (target, conditionDict) => {
    for (const [key, value] of Object.entries(conditionDict)) {
        target[key] = value
    }
}
```

### 1. 'info'란 무엇인가?

``` javascript
try {
        const info = answerInfo[paramKey]
        const type = info['type']
    } catch (err) {
        return;
    }
```

인자로 받은 'paramKey'를 사용해서, 'info' data에서 원하는 내용을 추출하는 부분이다.
'info' 에는 어떤 내용이 들어 있는지, 이 함수를 통해 어떠한 부분을 뽑아내는지?

<b> 'info' 데이터 일부분 </b>
```
"commute_type" : {
        "type" : "choose",
        "is_where" : false,
        "list" : [
            {
                "item_name" : "대중교통",
                "condition_name" : "commute_type",
                "condition_value" : "transit"
                
            },
            {
                "item_name" : "자동차",
                "condition_name" : "commute_type",
                "condition_value" : "driving"
            }
        ]
    }
```

User가 챗봇에 대답하게 될 모든 정보에 대한 대응값이 저장되어있다.
위의 일부 데이터를 예시로 들자면,

> 
Chat : 통근하는 방법(commute_type)을 선택해주세요
User : ["대중교통" / "자동차"]  중 택 1 답변

User가 선택한 내역에 대응한 값을 가지고 있다.

다시, 위의 일부 데이터를 예시로 정리해보자.
``` javascript
const info = answerInfo[paramKey]
 const type = info['type']
```
paramKey를 통해서 
info 데이터인 "phone" , "commute_type", ... "deposit". "monthly_rent" 중 "commute_type"의 'type'을 추출하는 것이다.
const type 에는 "choose" 가 저장 되겠다.

데이터의 type 에는 "choose" , "text" , "currency"
3가지 가 있다. User가 선택하는 것, text를 전송하는 것, 값을 전송하는 것.

### 2. 3가지 type 어떻게 처리되나?

1번에서 paramKey 인자를 통해 type을 알아냈다. 
각 type별로 어떻게 사용되는지 파악해보겠다.

<b> TEXT</b>
``` javascript
 if (type == 'text') {
        let key = info['condition_name']
        result[key] = paramValue
    }
```
User가 입력한 값인 paramValue를
condition_name : paramvalue 형식으로 result에 저장한다.

단순 질문과 대답을 하나의 쌍으로 연결하는 것.

개인적인 질문
key 라는 변수를 선언하고 저장할 필요 없이
result[paramKey] = paramValue 해도 되지 않았을까?
parmaKey == info['condition_name'] 이니 말이다.

<b> CHOOSE </b>
``` javascript
 else if (type == 'choose') {
        let list = info['list']
        for (let entry of list) {
            let key = entry['condition_name']
            let value = entry['condition_value']
            if (paramValue == entry['item_name']) {
                result[key] = value;
                break;
```

Choose 라는 것은, 여러 개 중 선택한다는 뜻이다.
즉, 선택하는 List가 있다는 것이다.

해서, 선택지 List를 가져오고, 각각 선택항목과, User가 선택한 paramValue와 비교한다.
User가 선택한 것이 나오면 Text와 마찬가지로
질문과 대답에 대한 값을 result 에 저장한다.

<b> CURRENCY </b>
``` javascript
else if (type == 'currency') {
        const { amount } = JSON.parse(paramValue);
        let key = info['condition_name']
        result[key] = amount
```

위와 마찬가지로 쌍을 만들어서 result에 저장하는 방식
다만 currency 이다보니, 가격을 나타내는 수와, 단위를 나타내는 문자열의 정보를 JSON.parse로 처리하는 것이 들어있다.

<br>

## 궁금증
코드를 이해하기로는, paramKey 와 info['condition_name'] 의 값이 동일 한 것으로 생각이 된다.
그럼에도 따로 key라는 변수를 만들어서 info['condition_name']의 값을 저장해서 사용하는 이유가 따로 있는건지?

key 변수 선언 및 저장을 생략하고
result[paramkey] = paramValue 를 하게 되면 다른 문제가 있는것인지

**Comment by parkgeonhu** [comment]
```json
"hobby" : {
        "type" : "choose",
        "is_where" : true,
        "list" : [
            {
                "item_name" : "맛집 탐방",
                "condition_name" : "restaurant",
                "condition_value" : true
            },
            {
                "item_name" : "전시/영화 보기",
                "condition_name" : "cultulral_facility",
                "condition_value" : true
            },
            {
                "item_name" : "집에서 쉬기",
                "condition_name" : "convenience_store",
                "condition_value" : true
            }
        ]
    },
```
를 보시면 `paramKey 와 info['condition_name'] 의 값이 동일 한 것으로 생각이 된다.` 는 해결되셨을겁니다.

왜 저렇게 뒀냐면 질문에 선택지가 있을 때, db로 where 절 질의하는 변수는 달라야하기 때문입니다. hobby로 질의하면 안 나옵니다. 실제 db 스키마 보시면 restaurant, cultural_facility 등이 있기 때문입니다.

result[paramkey] = paramValue 역시 마찬가지입니다.
paramValue의 경우 expect_request.json 을 보시면 "{\"amount\": 0, \"unit\": \"원\"}", 이런 식으로 되어있는 것도 보실 수 있습니다. 이것을 db에 raw 하게 삽입하는 것이 아닌, 파싱 후 해야합니다.
